// <auto-generated />
namespace IMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:IMDB/Migrations/202205101423138_initilization.Designer.cs
    public sealed partial class initilization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initilization));
        
        string IMigrationMetadata.Id
        {
            get { return "202205101423138_initilization"; }
========
    public sealed partial class fixingDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixingDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131948261_fixingDelete"; }
>>>>>>>> origin/Edit_and_Delete:IMDB/Migrations/202205131948261_fixingDelete.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
