// <auto-generated />
namespace IMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:IMDB/Migrations/202205131209147_director.Designer.cs
    public sealed partial class director : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(director));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131209147_director"; }
========
    public sealed partial class fixErros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixErros));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131853388_fixErros"; }
>>>>>>>> origin/Edit_and_Delete:IMDB/Migrations/202205131853388_fixErros.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
